name: SSH Commands

on:
  schedule:
    - cron: '0 15 * * *' # UTC 时间，根据当前北京时间调整为：每天凌晨3点
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup SSH Keys
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -t rsa s2.serv00.com >> ~/.ssh/known_hosts
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy via SSH
      run: |
        ssh -i ~/.ssh/id_rsa zhitiaojun@s2.serv00.com "
          cd ~/domains/alist/
          ./alist stop
          ./alist start
        "
